/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM = 12.0;
const MARGIN_CARD_MEDIUM_2 =14.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_SMALL = 11.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_MEDIUM = 18.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_LARGE = 22.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;

const ICON_MEDIUM = 28.0;
const ICON_MEDIUM_2 = 40.0;
const ICON_LARGE = 60.0;


/// App Specific
const MAIN_BUTTON_HEIGHT = 60.0;
const MAIN_BUTTON_WIDTH = 380.0;
const WELCOME_SCREEN_ICON_HEIGHT = 300.0;
const WELCOME_SCREEN_ICON_WIDTH = 300.0;

const LOGIN_SCREEN_TOP_MARGIN = 70.0;
const LOGIN_SCREEN_TAB_BAR_VIEW_HEIGHT = 250.0;

const HORIZONTAL_MOVIE_LIST_HEIGHT = 300.0;
const MOVIE_ITEM_WIDTH = 140.0;
const MOVIE_ITEM_HEIGHT = 200.0;

const CIRCLE_AVATAR_ICON_SIZE = 50.0;
const PLAY_BUTTON_ICON_BACKGROUND_CONTAINER_SIZE = 50.0;
const GENRE_CHIP_HEIGHT = 45.0;
const MOVIE_DETAIL_ACTOR_IMAGE_ICON_SIZE = 65.0;
const MOVIE_DETAIL_SLIVER_APPBAR_HEIGHT = 300.0;
const MOVIE_SNACK_SECTION_HEIGHT = 260.0;

const MOVIE_TIME_LIST_HEIGHT = 88.0;
const DRAWER_TOP_SPACE_HEIGHT = 96.0;

const PAYMENT_CARD_WIDTH = 300.0;
