const HIVE_TYPE_ID_USER_VO = 1;
const HIVE_TYPE_ID_TOKEN_VO = 2;
const HIVE_TYPE_ID_CARD_VO = 3;
const HIVE_TYPE_ID_MOVIE_VO = 4;
const HIVE_TYPE_ID_ACTOR_VO = 5;
const HIVE_TYPE_ID_CINEMA_VO = 6;
const HIVE_TYPE_ID_SNACK_VO = 7;
const HIVE_TYPE_ID_TIMESLOT_VO = 8;

const BOX_NAME_USER_VO = "BOX_NAME_USER_VO";
const BOX_NAME_TOKEN_VO = "BOX_NAME_TOKEN_VO";
const BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const BOX_NAME_CINEMA_VO = "BOX_NAME_CINEMA_VO";
const BOX_NAME_PROFILE = "BOX_NAME_PROFILE";
const BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
const BOX_NAME_TIMESLOT_VO = "BOX_NAME_TIMESLOT_VO";